### ISSUE TITLE
XPF record stacking?

### ISSUE THREAD

**Issue by raybellis** [raybellis/draft-bellis-dnsop-xpf#11]
Is multi-tier XPF stacking actually required?

If there are multiple proxy tiers, wouldn't the server be more likely to be more interested in the original XPF packet, not the last one?

**Comment by Habbie** [comment]
:+1: to 'max one XPF per packet', and stripping unless administrator decides XPF should be preserved while forwarding.

**Comment by raybellis** [comment]
Stripping is inconsistent with servers generating REFUSED if an XPF RR is present when it shouldn't be.

**Comment by raybellis** [comment]
Resolved in f25d48750c937798c11b6851e5cdedc4b96fa7cf
