### ISSUE TITLE
State of submission to IETF

### ISSUE THREAD

**Issue by tomsanbear** [raybellis/draft-bellis-dnsop-xpf#15]
Since doing some digging on the IETF data tracker it seems the draft has been expired, and no more activity has been taken to push it through. I'm curious if there was a resolution, be it good or bad. I have some interest in making this record type available in other DNS servers when/if it's approved and assigned a RRType code.

**Comment by raybellis** [comment]
We're planning to re-submit it via the AD Sponsored route to publication, since DNSOP does not appear to be interested in taking it on.

**Comment by tomsanbear** [comment]
Sounds good, if you don't mind me asking is there a timeline you are expecting with this process? I am not familiar with IANA's bureaucracy.

**Comment by raybellis** [comment]
Sorry, not exactly, that's still TBD.   We're hoping to implement in BIND soon, which will put us in a stronger position to request publication on the basis that we're documenting an existing (and interoperable) mechanism that is in more than one implementation.

**Comment by tomsanbear** [comment]
Sounds good. Thanks for the extra information, I'll come back and reference the implementation I'm working on for CoreDNS at a later time.
