### ISSUE TITLE
presentation format

### ISSUE THREAD

**Issue by Habbie** [raybellis/draft-bellis-dnsop-xpf#3]
> 3.4.  Presentation Format
>  Since this is a "meta" RR that cannot appear in master format zone files no presentation format is defined.
> 
> Could you please define a Presentation Format so that "dig" and similar tools use a consistent format?
> 
> -- 
> Bob Harold

**Comment by raybellis** [comment]
Addressed by e9975b11dcd4ce6a5c1431dd917af0be1747131a
