### ISSUE TITLE
use IANA family numbers?

### ISSUE THREAD

**Issue by Habbie** [raybellis/draft-bellis-dnsop-xpf#9]
We use '4' and '6' to indicate v4 and v6. These numbers do not appear like that in any registry. edns-client-subnet and clientid use https://www.iana.org/assignments/address-family-numbers/address-family-numbers.xhtml. @arjenz noticed during wireshark implementation that our deviation makes his code longer as he cannot rely on the already present IANA list.

**Comment by Habbie** [comment]
IANA family numbers are 16 bits, this costs us our 4 bits of extensibility but we could use 65535 to signal some future extension perhaps.

**Comment by Habbie** [comment]
> These numbers do not appear like that in any registry

I lied - https://www.iana.org/assignments/version-numbers/version-numbers.xhtml

**Comment by Habbie** [comment]
So, the argument is somewhat weak but I'd still like to make a conscious decision here.

**Comment by rgacogne** [comment]
Since we have the original destination port, it should be possible to use that to infer whether the query was received over TLS (port 853) or QUIC (port TBD AFAIK).

**Comment by Habbie** [comment]
the QUIC port could be 80 or 443 as far as I know, but perhaps that's good enough, yes. But what do we put in the protocol field then? UDP?

**Comment by raybellis** [comment]
The 4 bit field in XPF indicates the L3 transport protocol version, but
we only support IP anyway.

**Comment by Habbie** [comment]
> I think we're talking about two different fields here.

Yes, I mixed up the two topics because they felt similar/related.

> Arguably a meta-value should be defined in the protocol
> registry that wouldn't be used on-the-wire (because QUIC uses UDP) but
> might be used to otherwise indicate that QUIC had been used ?

Yes, indeed. Shall I take this question to quic@ietf?

**Comment by Habbie** [comment]
Moved the QUIC stuff to #10

**Comment by arjenz** [comment]
Implemented lookup for RFC2780 / https://www.iana.org/assignments/version-numbers/version-numbers.xhtml in the Wireshark dissector, https://code.wireshark.org/review/#/c/22803/
So the only argument left now is being in sync with edns-client-subnet and clientid  :)

**Comment by raybellis** [comment]
On 26/07/2017 14:19, Arjen Zonneveld wrote:

> So the only argument left now is being in sync with edns-client-subnet
> and clientid :)

There's no argument - EDNS Client Subnet used the wrong one ;-)

Since clients only access DNS over IP, and prefix lengths have no
semantic meaning in some of the non-IP family AF_XXX protocols, why use
a registry with illegal values when the only sane ones are AF_INET and
AF_INET6.

**Comment by Habbie** [comment]
Alright, settled!

**Comment by raybellis** [comment]
BTW, the IANA Address Family Registry and the BSD socket AF_INET and AF_INET6 macros don't even use the same values.

**Comment by Habbie** [comment]
> BTW, the IANA Address Family Registry and the BSD socket AF_INET and AF_INET6 macros don't even use the same values.

I noticed that when `getnameinfo` refused to convert an IP in AF 4 ;)
